import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, TextInput } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { useCallback, useEffect, useState } from 'react';

import { Text, View } from '@/components/Themed';
import { createPartner, deletePartner, fetchPartners, type PartnerPayload, updatePartner } from '@/lib/api';
import { supabase } from '@/lib/supabase';
import type { Partner } from '@/lib/types';
import { useAuth } from '@/contexts/auth';

const empty = (): PartnerPayload => ({ image_url: '', caption: '', is_active: true, is_featured: false, display_order: 0 });

export default function PartnersScreen() { const { profile } = useAuth(); return profile?.role === 'admin' ? <AdminCarousel /> : <StudentCarousel />; }

function StudentCarousel() {
  const [slides, setSlides] = useState<Partner[]>([]); const [index, setIndex] = useState(0); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setSlides(await fetchPartners()); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, [load]);
  const current = slides[index];
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.container}><View style={s.header}><Text style={s.eyebrow}>COMUNIDADE JUNGLE</Text><Text style={s.title}>Parceiros Jungle</Text><Text style={s.subtitle}>Empresas da nossa comunidade</Text></View>{loading ? <ActivityIndicator color="#D7262E" /> : current ? <><Image source={{ uri: current.image_url }} style={s.image} /><View style={s.dots}>{slides.map((slide, item) => <Pressable key={slide.id} onPress={() => setIndex(item)} style={[s.dot, item === index && s.dotActive]} />)}</View>{current.caption ? <Text style={s.caption}>{current.caption}</Text> : null}<View style={s.controls}><Pressable onPress={() => setIndex((index - 1 + slides.length) % slides.length)} style={s.outline}><Text style={s.outlineText}>Anterior</Text></Pressable><Pressable onPress={() => setIndex((index + 1) % slides.length)} style={s.primary}><Text style={s.primaryText}>Próximo</Text></Pressable></View></> : <View style={s.empty}><Text style={s.emptyTitle}>Novidades em breve</Text><Text style={s.emptyText}>A vitrine dos parceiros está sendo preparada.</Text></View>}<Pressable onPress={load} style={s.refresh}><Text style={s.refreshText}>Atualizar</Text></Pressable></ScrollView></SafeAreaView>;
}

function AdminCarousel() {
  const [slides, setSlides] = useState<Partner[]>([]); const [form, setForm] = useState<PartnerPayload>(empty); const [editing, setEditing] = useState<Partner | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [showForm, setShowForm] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setSlides(await fetchPartners()); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 0); return () => clearTimeout(timer); }, [load]);
  function open(slide?: Partner) { setEditing(slide ?? null); setForm(slide ? { image_url: slide.image_url, caption: slide.caption, is_active: slide.is_active, is_featured: slide.is_featured, display_order: slide.display_order } : empty()); setShowForm(true); }
  async function choose() { if (!supabase) return; const client = supabase; const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permissão necessária', 'Permita o acesso às fotos para adicionar a imagem.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: 'images', allowsEditing: true, aspect: [1, 1], quality: 0.85 }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; const response = await fetch(asset.uri); const bytes = await response.arrayBuffer(); const ext = asset.mimeType?.split('/')[1] || 'jpg'; const path = `slides/${Date.now()}.${ext}`; const { error } = await client.storage.from('partner-media').upload(path, bytes, { contentType: asset.mimeType ?? `image/${ext}` }); if (error) return Alert.alert('Erro', error.message); setForm((value) => ({ ...value, image_url: client.storage.from('partner-media').getPublicUrl(path).data.publicUrl })); }
  async function save() { if (!form.image_url) return Alert.alert('Imagem obrigatória', 'Selecione uma imagem para o carrossel.'); setSaving(true); try { if (editing) await updatePartner(editing.id, form); else await createPartner(form); setShowForm(false); await load(); } catch (error) { Alert.alert('Erro', error instanceof Error ? error.message : 'Não foi possível salvar.'); } finally { setSaving(false); } }
  function remove(slide: Partner) { Alert.alert('Excluir slide', 'Deseja excluir esta imagem?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { await deletePartner(slide.id); await load(); } }]); }
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.container}><View style={s.header}><Text style={s.eyebrow}>ADMINISTRAÇÃO</Text><Text style={s.title}>Parceiros Jungle</Text><Text style={s.subtitle}>Imagens do carrossel</Text></View><Pressable onPress={() => open()} style={s.primaryWide}><Text style={s.primaryText}>Adicionar imagem</Text></Pressable>{loading ? <ActivityIndicator color="#D7262E" /> : slides.map((slide) => <View key={slide.id} style={s.adminRow}><Image source={{ uri: slide.image_url }} style={s.thumb} /><View style={s.adminText}><Text style={s.itemText}>{slide.caption || 'Sem texto'}</Text><Text style={s.itemMeta}>{slide.is_active ? 'Ativo' : 'Inativo'} · Ordem {slide.display_order}</Text></View><Pressable onPress={() => open(slide)}><Text style={s.outlineText}>Editar</Text></Pressable><Pressable onPress={() => remove(slide)}><Text style={s.deleteText}>Excluir</Text></Pressable></View>)}{showForm && <View style={s.form}><Text style={s.formTitle}>{editing ? 'Editar imagem' : 'Nova imagem'}</Text><Pressable onPress={choose} style={s.outline}><Text style={s.outlineText}>{form.image_url ? 'Trocar imagem' : 'Selecionar imagem'}</Text></Pressable>{form.image_url ? <Image source={{ uri: form.image_url }} style={s.preview} /> : null}<Text style={s.label}>Texto breve</Text><TextInput value={form.caption} onChangeText={(caption) => setForm((value) => ({ ...value, caption }))} multiline style={s.input} placeholderTextColor="#9CA3AF" /><Text style={s.label}>Ordem</Text><TextInput value={String(form.display_order)} onChangeText={(value) => setForm((item) => ({ ...item, display_order: Number(value) || 0 }))} keyboardType="numeric" style={s.input} /><Pressable onPress={() => setForm((value) => ({ ...value, is_active: !value.is_active }))} style={s.toggle}><Text style={s.label}>Exibir no carrossel</Text><Text style={form.is_active ? s.on : s.off}>{form.is_active ? 'Sim' : 'Não'}</Text></Pressable><View style={s.controls}><Pressable onPress={() => setShowForm(false)} style={s.outline}><Text style={s.outlineText}>Cancelar</Text></Pressable><Pressable disabled={saving} onPress={save} style={s.primary}><Text style={s.primaryText}>{saving ? 'Salvando...' : 'Salvar'}</Text></Pressable></View></View>}</ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({ safe:{flex:1,backgroundColor:'#111'},container:{gap:18,padding:24,paddingBottom:34},header:{gap:5,backgroundColor:'#111'},eyebrow:{color:'#D7262E',fontSize:12,fontWeight:'800'},title:{color:'#FFF',fontSize:30,fontWeight:'800'},subtitle:{color:'#9CA3AF',fontSize:15},image:{width:'100%',aspectRatio:1,borderRadius:8},dots:{flexDirection:'row',justifyContent:'center',gap:10,backgroundColor:'#111'},dot:{width:9,height:9,borderRadius:9,backgroundColor:'#555'},dotActive:{backgroundColor:'#D7262E'},caption:{color:'#D1D5DB',fontSize:15,textAlign:'center'},controls:{flexDirection:'row',gap:10,backgroundColor:'#111'},primary:{flex:1,minHeight:46,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:'#D7262E'},primaryWide:{minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:'#D7262E'},primaryText:{color:'#FFF',fontWeight:'800'},outline:{flex:1,minHeight:46,alignItems:'center',justifyContent:'center',borderRadius:8,borderWidth:1,borderColor:'#D7262E',backgroundColor:'#FFF'},outlineText:{color:'#D7262E',fontWeight:'800'},refresh:{minHeight:44,alignItems:'center',justifyContent:'center'},refreshText:{color:'#9CA3AF',fontWeight:'700'},empty:{gap:8,borderRadius:8,padding:20,backgroundColor:'#FFF'},emptyTitle:{color:'#151515',fontSize:18,fontWeight:'800'},emptyText:{color:'#6B7280'},adminRow:{flexDirection:'row',alignItems:'center',gap:10,borderRadius:8,padding:10,backgroundColor:'#FFF'},thumb:{width:52,height:52,borderRadius:6},adminText:{flex:1,gap:3,backgroundColor:'#FFF'},itemText:{color:'#151515',fontWeight:'800'},itemMeta:{color:'#6B7280',fontSize:12},deleteText:{color:'#B91C1C',fontWeight:'800'},form:{gap:12,borderRadius:8,padding:16,backgroundColor:'#FFF'},formTitle:{color:'#151515',fontSize:19,fontWeight:'800'},preview:{width:'100%',aspectRatio:1,borderRadius:8},label:{color:'#374151',fontSize:13,fontWeight:'800'},input:{minHeight:46,borderWidth:1,borderColor:'#E5E7EB',borderRadius:8,padding:10,color:'#151515',backgroundColor:'#FFF'},toggle:{flexDirection:'row',justifyContent:'space-between',padding:12,borderRadius:8,backgroundColor:'#F3F4F6'},on:{color:'#15803D',fontWeight:'800'},off:{color:'#6B7280',fontWeight:'800'} });
